status: ready
title: Icon Card
context:
  heading: Dom√§nenarchitektur
  text: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.
