language: node_js
node_js:
  - '8'
cache: yarn
script:
  - npm test
  - npm run dist
  - cat $TRAVIS_COMMIT > dist/site/release.txt
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: dist/site
    github_token:
      secure: ID7CNbzpYpgPiJuFgMVmAPreJCUBqIicMsBpfia6OIzIIhGiywkOUkQqU9P7LC/+53tlXl4C0QERu5tsvaKTBhuADXctIrphr0o7TzK+3Yc3t+wixpa3u0WOkCO66uEJTWRXw3R4idZI3kOdq0ug38ixETWpQhFVMpSi2J1X7qvz6YCWGaPru7qjcOM3LcjLlTYm5vHMD3rxW7gsNyHPwwYpLMC1ZqqEfMax6jtdy1rNKq5ltQQyZkoLd53PhTOGxjAk9sNedVEEEgHaIEswH0Wq1qNIVHFCmTUMHlIqifkiPAlg1yOHSoT0GhZ1MH3c3re2ldh0U80ysI66yBu1WBGYt2a/Oo6jic2odyfLj/Re0y+A7I4XhIvdPDcFPXOqAiR2+9myzHruGp1paM9NEamYEANDDzLPrxsP2ZbvtXRwdsSvmXPoD8Z7SoSbrtywq0x1uSyN/mhoCqFq9auOGGjmG6h1Z4OZUgDjHUEniJU3tOj9Aq3CYWFi/vU6GO4gElFtpObHlkkzQQtKSslwUpqdqJWdGkX6R4HzlFpg9hiEGTtlplM4tlXPT9fVLpEki71z2KYMLfGhk3ZsP9wfIJQFsCLDDqI+fJXDpDGhAi2oD0o/A7urNEK6ma9EMRHTN9sD0BiD/H1ku6fSxBxXWGEfqOPbGzTBwdY77npwCJo=
    on:
      branch: master
      tags: true
  - provider: npm
    skip_cleanup: true
    email: mail@robert-glaser.de
    api_key:
      secure: rU1W4ZTxjH73GZhCzdTGFSDnZEEgUTlhzLzHbV+kXdfL8ogUDFKG7GS3FTTgQ7TKjj4ip6vXoBa1fp3oOaOzcu7cgQXhisx1uIrnV1LYfVCYKBmjs/e5pSE0yTqmJFB3ixrwmAhiTYC61JM6jCTkzGejOOQWU6dx/161ZFSZyEv3M8DoUM57T/aoGcwYrqYbA3axhNpcxiLv39SitbN/OBNHYbocUUiocShLdGVA+g12eOscGCIHxbz/TgMEjLHd4dQlnnjklIbEc56Yspn0dDUVfbG7N4p0eTa0u2Q5K2UGDqs/ltTGBsUmInkQQqte/A4qE70kQYVtcHtqFVTJ1Ereh3MFNSnB6pooFkd5zz3lpBtnvQxLQrLT2r8pzq41Nw2l5RnD90heefZNn5clj0zwcN3Ax1D02eOPh0dhKAe4iSvwZrzCV6PjhoYYTxAb1j2Jz875hm8IGKeFSswEwK9/o/uQpmyiNX0Cl+VpXOkvt/UAe3qkE9MQ/pCEoy57STd0VANOebrEhBiHntPZ8Mr4kIT+LAuZAe0AIniH2QBn10rXM5m5hiKAqpJosCqLdjpC8iwRE/juO85oXGkriqOxRGmdT5/Gp6t/3Y0BCLURKtLr0RNcmJ66NxzGtWoM1yW87Kdqn8BQLW5/5kDpFEssSipUAmjDPrMbM/QYP40=
    on:
      tags: true
      repo: innoq/innoq-styleguide
notifications:
  slack:
    secure: D7JQmWSVremDSAChLO2Qgl3yA1I3sH9zoD5RBNLGY05c07sQtW0Dy/VQrAueHZdYA9TS4ryZ4lLKwdSQ2eUodhPDm9iAO8vbfWfieCrlipHPx2/xjyDnHyKId+/tX3CqkA9nYTs1E4Txw+eUBQsLCvk3YJg6Cll55Gx6O8HGisQtNON1RMr3tmO4piTTky9zsH8HU0grunLfuYK/2B9/5vprzr51xPa2rRMh2nGos8VtxwHaBctKEGEBjdRaKycKQhfO6NVK8rjT64PxxHTR4gnvJY1wa4NdDhPfOEE/VHY/dpSvpbqVmz2w5/cvb9JucZVHXezqDhAS0UouSBeU5SKBoJ7bt0C4jv9viCVHGBDvwzeqGkZbeQC5rrLp6/SzzSzEqmoARC7bFcRk1s1/2I5OQE8YpJhRDe3zeWZWsm+Tf7Ai+QrGZOL2DgS0JuxzFlrOto6ZpvchFM19f329fc/HJF3po9U8KYLLhxx1ROlTPBIduCURKLP+Wc487DCifr9FiaG3ewgrE0EjyzDTw+OVSYcgFhxwuLFFc1dQbxu7JAm354e/BvgXgsPmHZwKksT3LukuP2TYy0klYS2wQqjZzB8Ew05Ka1U3C2NBOlWjZZxA+0BP7SsDx2xaYpdkhg4DW0JWH2SR1q3j5FxV9P0pbV4D/d7vtwKQnv0suxo=
    on_success: change
    on_failure: always
