status: ready
title: Color Container
context:
  text: Der Ablauf ist bei längeren Reviews grundsätzlich der gleiche. Interviews und Analysen benötigen bei größeren Reviews allerdings deutlich mehr Zeit, die Abstimmungsphase und die Erstellung des Ergebnisberichts dauern dagegen nur geringfügig länger.
