status: wip
context:
  headline: Soziotechnische Architekturen als Wettbewerbsvorteil
  text: >
    In der heutigen Geschäftswelt dient technologischer Fortschritt nicht nur der
    Effizienzsteigerung, sondern eröffnet auch neue Geschäftsfelder, die ohne diese Technologien
    undenkbar wären. Die optimale Nutzung neuer Technologien wird damit zu einem zentralen
    Wettbewerbsvorteil. IT-Entscheider:innen stehen jedoch zunehmend vor der
    Herausforderung, dass Technologie allein nicht ausreicht. Stattdessen müssen Unternehmen
    sich als soziotechnisches System verstehen, in dem technische Systeme und menschliche
    Interaktionen eng miteinander verzahnt sind.
  linkText: Mehr erfahren
  link: "#"
